name: Actions Build OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      method: 
        description: |
          编译方式选择
        required: false
        default: "Call-Build-Source"
        type: choice
        options:
          - Call-Build-openwrt
          - Call-Build-openwrt-GZ
      
      version:
        description: |
          选择 OpenWrt 版本
        required: false
        default: "24.10.0"
        type: choice
        options:
          - 23.05.5
          - 24.10.0
      
      source_name:
        description: |
          选择编译源码
        required: false
        default: "all"
        type: choice
        options:
          - all
          - sse_msg
          - api
          - wxpusher
          - sub
          - openssl.cgi
          - v2ray.cgi
          - page.cgi
          - sub.cgi
          - netlink
          
jobs:
  Call-Build-Source:
    if: ${{ inputs.method == 'Call-Build-Source' }}
    uses: ./.github/workflows/Call-Build-Source.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      source_name: ${{ inputs.source_name }}
  
  Call-Build-Source-GZ:
    if: ${{ inputs.method == 'Call-Build-Source-GZ' }}
    uses: ./.github/workflows/Call-Build-Source-GZ.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      source_name: ${{ inputs.source_name }} 