name: Actions Build OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:  
      version:
        description: 选择 OpenWrt 版本
        required: false
        default: "24.10.0"
        type: choice
        options:
          - 23.05.5
          - 24.10.0
      
      source_name:
        description: 选择编译源码
        required: false
        default: "all"
        type: choice
        options:
          - all
          - sse_msg
          - ws_msg
          - docker_web
          - api
          - wxpusher
          - sub
          - openssl.cgi
          - v2ray.cgi
          - page.cgi
          - sub.cgi
          - netlink
      
      pack:
        description: 是否打包(TAR.GZ)
        default: false
        type: boolean
        
jobs:
  Call-Build-OpenWrt:
    uses: ./.github/workflows/Call-Build-openwrt.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      source_name: ${{ inputs.source_name }}
      pack: ${{ inputs.pack }}