name: Actions Build GO 

on:
  workflow_dispatch:
    inputs:
      source_name:
        description: 选择编译软件源码
        required: false
        default: "all"
        type: choice
        options:
          - all
          - NapCat/NapCat_Api
          - NapCat/NapCat_Service
          - Photopea
          - MDDNS
          
env:
  Build_PATH: "${{ github.workspace }}/Build"
  
jobs:
  build:
    name: build ${{ inputs.source_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@main
        with:
          go-version: "1.25"
      
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v4
        with:
          version: 5.1.1
          install-only: true
      
      - name: Configure environment variables
        run: |
          test -d "${{ env.Build_PATH }}" || mkdir -p "${{ env.Build_PATH }}"
          echo "Name=$(basename ${{ inputs.source_name }})" >> $GITHUB_ENV
          echo "SOURCE_PATH=$(mktemp -d)" >> $GITHUB_ENV
          echo "✅ UPX版本：$(upx --version)"
          
      - name: Download and Source
        working-directory: ${{ env.SOURCE_PATH }}
        id: source
        env:
          OPENWRT_GOLANG_COMMIT: ${{ secrets.OPENWRT_GOLANG_COMMIT }}
          url: https://3wlh:${{ secrets.TOKEN_GITHUB }}@github.com/3wlh/Source
        run: |
          echo "✅ 拉取仓库：3wlh/Source"
          git clone --depth=1 ${url} $(pwd)/Source
          test -d "Source/GO" && mv Source/GO $(pwd)
          test -d "GO" && rm -rf Source
          echo "status=success" >> $GITHUB_OUTPUT
          
      - name: Build Source
        if: (steps.source.outputs.status == 'success')
        working-directory: ${{ env.SOURCE_PATH }}
        id: build_source
        env: 
          Name: ${{ env.Name }}
        run: |
          test -d "GO/${{ inputs.source_name }}" && cd "GO/${{ inputs.source_name }}"
          echo "Time=$(date "+%Y.%m.%d_%H%M%S")" >> $GITHUB_ENV
          mkdir -pm 775 ${{ env.Build_PATH }}
          echo "✅ 编译软件目录：$(pwd)"
          export CGO_ENABLED=0
          echo "✅ 下载依赖：${Name}"
          go mod tidy && go mod download
          for os in linux; do
            for arch in amd64 arm64; do
              echo "📦 编译 $Name-$os-$arch"
              export GOOS=$os && export GOARCH=$arch && go build -ldflags "-s -w" -o ${{ env.Build_PATH }}/$Name-$os-$arch        
              done
          done               
          # 设置输出变量
          if [ -d "${{ env.Build_PATH }}" ] && [ "$(ls -A ${{ env.Build_PATH }})" ]; then
            upx -9 ${{ env.Build_PATH }}/*
            echo "✅ 编译成功"
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "❌ 编译失败"
          fi
      
      - name: Delete GitHub Release
        if: (steps.build_source.outputs.status == 'success')
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: GitHub-Actions_${{ env.Name }}
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Release
        if: (steps.build_source.outputs.status == 'success')
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: GitHub-Actions_${{ env.Name }}
          name: GO：${{ env.Name }}
          body: |
            ## 编译信息
            - 编译时间：`${{ env.Time }}`
          files: ${{ env.Build_PATH }}/*