name: Call Build OpenWrt GZ

on:
  workflow_call:
    inputs:
      version:
        type: string
      source_name:
        type: string

env:
  CACHE_PATH: /tmp/.cache
  Build_PATH: ${{ github.workspace }}/Build
  PACKAGE_NAME: ${{ inputs.source_name }}
  SOURCE: OpenWrt/${{ inputs.Source_name }}/
  TZ: Asia/Shanghai
  UPLOAD_BIN_DIR: true

jobs:
  jod_compile:
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64_generic]      
    steps: 
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Install Dependencies
        run: |
          # DEBIAN_FRONTEND=noninteractive sudo apt-get install -y ccache gettext libncurses5-dev xsltproc
          #sudo apt-get remove gcc g++
      
      - name: Create Directories
        run: |
          echo "SOURCE_PATH=$(mktemp -d)" >> $GITHUB_ENV
          
      - name: Download and Unzip ToolChain
        uses: 3wlh/actions/openwrt/toolchain@main
        id: toolchain
        with:
          arch: ${{ matrix.arch }}
          version: ${{ inputs.version }}
          path: ${{ env.CACHE_PATH }}

      - name: Download and Source
        if: (steps.toolchain.outputs.status == 'success')
        working-directory: ${{ env.SOURCE_PATH }}
        id: source
        run: |
          git clone https://3wlh:${{ secrets.TOKEN_3WLH }}@github.com/3wlh/Source
          test -d "Source/C++/OpenWrt" && mv Source/C++/OpenWrt ./
          test -d "OpenWrt" && rm -rf Source
          ls
          echo "status=success" >> $GITHUB_OUTPUT
        
      - name: Build and Source
        if: (steps.source.outputs.status == 'success')
        working-directory: ${{ env.SOURCE_PATH }}
        id: build
        run: |
          source /etc/profile
          ls
          cd "${{ env.PACKAGE_NAME }}"
          files=$(find . -type f -name "*.cpp")
          Argv="-Os -s"
          if [ -n "$files" ]; then
            echo ${files}
            g++ ${files} -o ${{ env.Build_PATH }}/${{ env.PACKAGE_NAME }}-${{ matrix.arch }} ${Argv}
          else
            files=$(find . -type f -name "*.c")
            echo ${files}
            gcc ${files} -o ${{ env.Build_PATH }}/${{ env.PACKAGE_NAME }}-${{ matrix.arch }} ${Argv}
          fi
          echo "status=success" >> $GITHUB_OUTPUT
          cd -
          
      - name: Upload to bin directory
        uses: actions/upload-artifact@main
        if: steps.build.outputs.status == 'success' && ${{env.UPLOAD_BIN_DIR}} == 'true'
        with:
          name: ${{ env.PACKAGE_NAME }}-${{ matrix.arch }}
          path: ${{ env.Build_PATH }}/${{ env.PACKAGE_NAME }}-${{ matrix.arch }}

  jod_release:
    name: Build for ${{ matrix.arch }}
    needs: jod_compile
    runs-on: ubuntu-latest
    env:
      Time: ${{ needs.initial.outputs.time }}
    steps:
      - name: Create Directory
        run: |
          test -d "${{ env.PACKAGE_NAME }}" || mkdir -p "${{ env.PACKAGE_NAME }}"
      
      
      
      - name: Download ${{ env.PACKAGE_NAME }}
        uses: actions/download-artifact@main
        with:
          path: ${{ env.PACKAGE_NAME }}
          merge-multiple: true
      
      - name: Package directory
        id: pack
        run: |
          cd ${{ env.PACKAGE_NAME }}
          tar -zcvf ${{ env.PACKAGE_NAME }}.tar.gz *
          test -f "${{ env.PACKAGE_NAME }}.tar.gz" && echo "status=success" >> $GITHUB_OUTPUT
          # cp -f ${{ env.PACKAGE_NAME }}.tar.gz ${{ env.PACKAGE_NAME }}/
          
      - name: Create Edit info
        run: |
          sudo timedatectl set-timezone "${TZ}"
          echo "## 编译时间：\`$(date "+%Y.%m.%d_%H%M%S")\`" > info.md
          echo "## [![Github](https://img.shields.io/badge/Release文件可在国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge)](https://ghproxy.net/)" >> info.md
          echo "## 软件信息：" >> info.md
          echo "* SDK版本 \`${{ inputs.version }}\`" >> info.md
    
      - name: Delete GitHub Release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: GitHub-Actions_${{ env.PACKAGE_NAME }}
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload to Release
        if: steps.pack.outputs.status == 'success'
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: GitHub-Actions_${{ env.PACKAGE_NAME }}
          name: OpenWrt：${{ env.PACKAGE_NAME }}
          body: |
            ## 编译信息
            - 编译时间：`${{ env.Time }}`
          files: ${{ env.PACKAGE_NAME }}/*