name: Call Build OpenWrt

on:
  workflow_call:
    inputs:
      version:
        type: string
      source_name:
        type: string

env:
  PACKAGE_NAME: ${{ inputs.source_name }}
  SOURCE: OpenWrt/${{ inputs.Source_name }}/
  Download_URL: https://downloads.openwrt.org/releases/${{ inputs.Version }}/targets
  PATH_CACHE: /tmp/.cache
  TZ: Asia/Shanghai
  UPLOAD_BIN_DIR: true

jobs:
  jod_initial:
    name: Acquisition Time
    runs-on: ubuntu-latest
    outputs:
      time: ${{steps.output_time.outputs.time}}
    steps: 
      - name: output Time
        id: output_time
        run: |
          sudo timedatectl set-timezone "${TZ}"
          echo "time=$(date "+%Y.%m.%d_%H%M%S")" >> $GITHUB_OUTPUT
          
      - name: Delete GitHub Release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: GitHub-Actions_${{ env.PACKAGE_NAME }}
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

  jod_release:
    name: Build for ${{ matrix.arch }}
    needs: jod_initial
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64_generic
            toolchain_url_path: layerscape/armv8_64b
            toolchain_name: -toolchain-.*-armv8_64b_
          - arch: x86_64
            toolchain_url_path: x86/64
            toolchain_name: -toolchain-.*-x86-64_

    env:
      SDK_NAME: ${{ matrix.toolchain_name }}
      Time: ${{ needs.jod_initial.outputs.time }}
      Build_PATH: ${{ github.workspace }}/Build
      SDK_URL_PATH: ${{ matrix.toolchain_url_path }}
    steps: 
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Setup Cache
        uses: actions/cache@main
        with:
          path: ${{ env.PATH_CACHE }}
          key: ${{ matrix.arch }}-${{ inputs.Version }}
      
      - name: Install Dependencies
        run: |
          # DEBIAN_FRONTEND=noninteractive sudo apt-get install -y ccache gettext libncurses5-dev xsltproc
          # sudo apt-get remove gcc g++
      
      - name: Set executable permissions
        run: |
          sudo chmod -R +x $(pwd)/.github/.sh/
          find $(pwd)/.github/.sh/ -name "*.sh" -exec sudo bash -c 'ln -sf "$0" "/bin/$(basename ${0%.*})"' {} \;
          
      - name: Configure environment variables
        run: |
          echo -e "\e[1;32m "$(g++ --version | head -n 1)" \e[0m"
          echo -e "\e[1;32m "$(gcc --version | head -n 1)" \e[0m"
          test -d "${{ env.Build_PATH }}" || mkdir -p "${{ env.Build_PATH }}"
          test -d "${{ env.PATH_CACHE }}" || mkdir -p "${{ env.PATH_CACHE }}"
          echo "SOURCE_PATH=$(mktemp -d)" >> $GITHUB_ENV
          
      - name: Download and Unzip ToolChain
        id: sdk
        run: |
          cd "${{ env.PATH_CACHE }}"
          if [[ $(du -s "${{ env.PATH_CACHE }}" | awk '{ print $1}') -lt 10240 ]]; then
            echo -e "\e[1;32m Start downloading the SDK \e[0m"
            Status="$(Download_sdk ${{ env.Download_URL }}/${{ env.SDK_URL_PATH }} ${{ env.SDK_NAME }})"
            [[ -n "Status" ]] || exec
          fi
          BIN="$(find ${{ env.PATH_CACHE }} -type l -name "*-linux-gcc" -print0 | xargs -0 dirname)"
          #echo "cpp=$(find . -type l -name "*-linux-g++" | xargs -i basename {})" >> $GITHUB_ENV
          #echo "c=$(find . -type l -name "*-linux-gcc" | xargs -i basename {})" >> $GITHUB_ENV
          file=("g++" "gcc" "c++" "cpp" "ld" "as")
          for name in "${file[@]}"; do
            find $(pwd) -type f -name "*-linux-*-${name}.bin" -exec sudo ln -sf {} /usr/bin/${name} \;
          done
          sudo sed -i '$a\export PATH=$PATH:'"${BIN}" /etc/profile
          sudo sed -i '$a\export STAGING_DIR='"${BIN%/*}" /etc/profile
          echo "status=success" >> $GITHUB_OUTPUT
          cd -

      - name: Download and Source
        id: source
        if: steps.sdk.outputs.status == 'success'
        env:
          OPENWRT_GOLANG_COMMIT: ${{ secrets.OPENWRT_GOLANG_COMMIT }}
        run: |
          cd "${{ env.SOURCE_PATH }}"
          git clone https://3wlh:${{ secrets.TOKEN_3WLH }}@github.com/3wlh/Source
          test -d "Source/C++/OpenWrt" && mv Source/C++/OpenWrt ./
          test -d "OpenWrt" && rm -rf Source
          echo "status=success" >> $GITHUB_OUTPUT
          cd -
                 
      - name: Build and Source
        id: build
        if: steps.source.outputs.status == 'success'
        run: |
          source /etc/profile
          echo ${PATH}
          echo -e "\e[1;32m "$(g++  --version | head -n 1)" \e[0m"
          echo -e "\e[1;32m "$(gcc --version | head -n 1)" \e[0m"
          cd "${{ env.SOURCE_PATH }}"
          # SOURCE=$(find . -type f -name "*.cpp" -exec basename {} \;)
          SOURCE=$(find . -type f -name "*.cpp")
          Argv="-Os -s"
          if [ -n "${SOURCE}" ]; then
            echo ${SOURCE}
            # ${{ env.CXX }} -fsigned-char ${CPP} -o ${{ env.Build_PATH }}/${{ env.PACKAGE_NAME }}-${{ matrix.arch }}
            # 优化大小
            g++ ${SOURCE} -o ${{ env.Build_PATH }}/${{ env.PACKAGE_NAME }}-${{ matrix.arch }} ${Argv}
          else
            # SOURCE=$(find . -type f -name "*.c" -exec basename {} \;)
            SOURCE=$(find . -type f -name "*.c")
            echo ${SOURCE}
            gcc ${SOURCE} -o ${{ env.Build_PATH }}/${{ env.PACKAGE_NAME }}-${{ matrix.arch }} -Os
          fi
          echo "status=success" >> $GITHUB_OUTPUT
          cd -

      - name: Create Edit info
        run: |
          echo "## 编译时间：\`${{ env.Time }}\`" > info.md
          echo "## [![Github](https://img.shields.io/badge/Release文件可在国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge)](https://ghproxy.net/)" >> info.md
          echo "## 软件信息：" >> info.md
          echo "* SDK版本 \`${{ inputs.version }}\`" >> info.md

      - name: Upload to bin directory
        uses: actions/upload-artifact@main
        if: steps.build.outputs.status == 'success' && ${{env.UPLOAD_BIN_DIR}} == 'true'
        with:
          name: ${{ env.PACKAGE_NAME }}-${{ matrix.arch }}_${{ env.Time }}
          path: ${{ env.Build_PATH }} 

      - name: Upload to Release
        if: steps.build.outputs.status == 'success'
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: GitHub-Actions_${{ env.PACKAGE_NAME }}
          name: OpenWrt：${{ env.PACKAGE_NAME }}
          body: |
            ## 编译信息
            - 编译时间：`${{ env.Time }}`
          files: ${{ env.Build_PATH }}/*