name: Call Build OpenWrt GZ

on:
  workflow_call:
    inputs:
      version:
        type: string
      source_name:
        type: string

env:
  PACKAGE: ${{ inputs.source_name }}
  CACHE_PATH: /tmp/.cache
  Build_PATH: ${{ github.workspace }}/Build
  TZ: Asia/Shanghai
  UPLOAD_BIN_DIR: true

jobs:
  jod_compile:
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64_generic]      
    steps: 
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Install Dependencies
        run: |
          # DEBIAN_FRONTEND=noninteractive sudo apt-get install -y ccache gettext libncurses5-dev xsltproc
          #sudo apt-get remove gcc g++
      
      - name: Create Directories
        run: |
          # ✅初始化设置
          echo "SOURCE_PATH=$(mktemp -d)" >> $GITHUB_ENV
          
      - name: Download and Unzip ToolChain
        uses: 3wlh/actions/openwrt/toolchain@main
        id: toolchain
        with:
          arch: ${{ matrix.arch }}
          version: ${{ inputs.version }}
          path: ${{ env.CACHE_PATH }}

      - name: Download and Source
        if: (steps.toolchain.outputs.status == 'success')
        working-directory: ${{ env.SOURCE_PATH }}
        id: source
        run: |
          # ✅拉取编译源码
          git clone https://3wlh:${{ secrets.TOKEN_3WLH }}@github.com/3wlh/Source
          test -d "Source/C++/OpenWrt" && mv Source/C++/OpenWrt ./
          test -d "OpenWrt" && rm -rf Source
          echo "status=success" >> $GITHUB_OUTPUT
        
      - name: Build and Source
        if: (steps.source.outputs.status == 'success')
        working-directory: ${{ env.SOURCE_PATH }}
        id: build
        run: |
          # ✅开始编译源码
          source /etc/profile
          cd "OpenWrt/${{ env.PACKAGE }}"
          files=$(find . -type f -name "*.cpp")
          Argv=""
          echo "✅源码文件: ${files}"
          if [ -n "$files" ]; then
            echo "${files}"
            g++ -Os ${files} -o ${{ env.Build_PATH }}/${{ env.PACKAGE }}-${{ matrix.arch }} ${Argv}
          else
            files=$(find . -type f -name "*.c")
            echo ${files}
            gcc -Os ${files} -o ${{ env.Build_PATH }}/${{ env.PACKAGE }}-${{ matrix.arch }} ${Argv}
          fi
          echo "status=success" >> $GITHUB_OUTPUT
          cd -
          
      - name: Upload to bin directory
        uses: actions/upload-artifact@main
        if: steps.build.outputs.status == 'success' && ${{env.UPLOAD_BIN_DIR}} == 'true'
        with:
          name: ${{ env.PACKAGE }}-${{ matrix.arch }}
          path: ${{ env.Build_PATH }}/${{ env.PACKAGE }}-${{ matrix.arch }}

  jod_release:
    name: Build for ${{ matrix.arch }}
    needs: jod_compile
    runs-on: ubuntu-latest
    env:
      Time: ${{ needs.initial.outputs.time }}
    steps:
      - name: Create Directory
        run: |
          # ✅初始化设置
          test -d "${{ env.PACKAGE }}" || mkdir -pm 755 "${{ env.PACKAGE }}"

      - name: Download ${{ env.PACKAGE }}
        uses: actions/download-artifact@main
        with:
          path: ${{ env.PACKAGE }}
          merge-multiple: true
      
      - name: Package directory
        id: pack
        run: |
          cd ${{ env.PACKAGE }}
          tar -zcvf ${{ env.PACKAGE }}.tar.gz *
          test -f "${{ env.PACKAGE }}.tar.gz" && echo "status=success" >> $GITHUB_OUTPUT
          # cp -f ${{ env.PACKAGE }}.tar.gz ${{ env.PACKAGE }}/
          
      - name: Delete GitHub Release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: GitHub-Actions_${{ env.PACKAGE_NAME }}
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload to Release
        if: steps.pack.outputs.status == 'success'
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: GitHub-Actions_${{ env.PACKAGE_NAME }}
          name: OpenWrt：${{ env.PACKAGE_NAME }}
          body: |
            ## 软件信息：
            - 编译时间：`${{ env.Time }}`
            - SDK版本: `${{ inputs.version }}`
          files: ${{ env.PACKAGE_NAME }}/*